"""Реинициализация

Revision ID: 156f373c56bc
Revises: f34dc9ed5412
Create Date: 2025-03-16 20:16:43.366607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156f373c56bc'
down_revision = 'f34dc9ed5412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('randomQuestions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('randomQuestions')

    # ### end Alembic commands ###
