"""Добавил новый столбец type

Revision ID: 3c206af5fbbd
Revises: 66b56c017f67
Create Date: 2025-04-03 00:29:26.362825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c206af5fbbd'
down_revision = '66b56c017f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=256), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=256), nullable=True))

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
