"""Добавил новый столбец type

Revision ID: 66b56c017f67
Revises: b902e7fc01ff
Create Date: 2025-04-03 00:27:59.147010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b56c017f67'
down_revision = 'b902e7fc01ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
