"""Реинициализация

Revision ID: 80353206f662
Revises: 
Create Date: 2025-03-16 20:10:35.182159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80353206f662'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime1', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('datetime1')

    # ### end Alembic commands ###
