"""Реинициализация

Revision ID: b902e7fc01ff
Revises: 156f373c56bc
Create Date: 2025-03-16 20:18:05.733761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b902e7fc01ff'
down_revision = '156f373c56bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('randomQuestions',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('randomQuestions',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
