"""Реинициализация

Revision ID: c2208c395cef
Revises: f7b9ee00ca6e
Create Date: 2025-03-16 20:13:14.208814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2208c395cef'
down_revision = 'f7b9ee00ca6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uhuh', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('uhuh')

    # ### end Alembic commands ###
