"""Реинициализация

Revision ID: f34dc9ed5412
Revises: c2208c395cef
Create Date: 2025-03-16 20:13:42.571936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34dc9ed5412'
down_revision = 'c2208c395cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('uhuh')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uhuh', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
