"""Реинициализация

Revision ID: f7b9ee00ca6e
Revises: 80353206f662
Create Date: 2025-03-16 20:11:30.745958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b9ee00ca6e'
down_revision = '80353206f662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('datetime1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime1', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
